### ISSUE TITLE
Windows support (full desktop support)

### ISSUE THREAD

**Issue by Lamorak** [gdg-berlin-android/ZeBadge#221]
Don't worry, I'm working on it 😅 
It actualy works, I'm just trying to simplify gradle config.

**Comment by mariobodemann** [comment]
@Lamorak Long time no see, but do you have an update on this one?

**Comment by Lamorak** [comment]
Jein, it works on windows, but not reliably. It is hard to determine which USB device is ze badge so I had to hardcode it and the image that I sent to ze badge has wrong scale. I'll try to make a PR at least for the minimal setup..

**Comment by mariobodemann** [comment]
Sounds great, thanks. 

Yeah let's irritate on it and maybe the community can take a look, refine it or something.

Thanks again for looking into it.

**Comment by alisen** [comment]
https://github.com/gdg-berlin-android/ZeBadge/pull/238
